### PR TITLE
Update runtime to 24.08

### PR DESCRIPTION
**Pull request by jakobjakobson13**

### CODE REVIEW

**Comment by jakobjakobson13** [comment]
See https://github.com/flathub/org.freedesktop.Sdk.Extension.texlive/issues/163#issuecomment-2345348435

**Comment by joshua-stone** [comment]
@jakobjakobson13 Looks like a new release was tagged:

https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/releases/freedesktop-sdk-24.08.1

```
$ flatpak remote-info flathub org.freedesktop.Sdk//24.08

Freedesktop SDK - Tools and headers for developing applications

        ID: org.freedesktop.Sdk
       Ref: runtime/org.freedesktop.Sdk/x86_64/24.08
      Arch: x86_64
    Branch: 24.08
   Version: freedesktop-sdk-24.08.1
   License: MIT
Collection: org.flathub.Stable
  Download: 615.4 MB
 Installed: 1.7 GB

    Commit: 9696fa2f512525b6ad7e65a7117e1013d0854f979d4f873bf3908010b1565878
    Parent: 96d3ff6ee86b27240d8d3653e58ccbf0e9761d9fbdfd472174bbf3e50e63d49d
   Subject: freedesktop-sdk-24.08.1-0-gb1a8aa87c560f19e725073b710fe7eee0117393b
      Date: 2024-09-13 17:59:59 +0000
```

Can you retry building?

**Comment by joshua-stone** [comment]
@jakobjakobson13 Looks like it works:

```
$ flatpak install https://dl.flathub.org/build-repo/129840/org.freedesktop.Sdk.Extension.texlive.flatpakref


        ID                                           Branch        Op       Remote               Download
 1. [✓] org.freedesktop.Sdk.Extension.texlive        24.08         i        texlive-origin       3.5 GB / 5.8 GB

Installation complete.
```

```
$ flatpak run --env="PATH=/app/bin:/usr/bin:/lib/sdk/texlive/bin:/lib/sdk/texlive/bin/$(uname -m)-linux" --runtime=org.freedesktop.Sdk//24.08 --command=tex org.freedesktop.Sdk.Extension.texlive//24.08 --version
TeX 3.141592653 (TeX Live 2024 - Flatpak)
kpathsea version 6.4.0
Copyright 2024 D.E. Knuth.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the TeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the TeX source.
Primary author of TeX: D.E. Knuth.
```

Is there anything else to test before merging?

**Comment by jakobjakobson13** [comment]
I would like to update dvisvgm as well but that lead to the fail of https://buildbot.flathub.org/#/builders/6/builds/146772

**Pull request merged**
