### PR TITLE
Build from source

### PR DESCRIPTION
**Pull request by jakobjakobson13**
basic build procedure works, however the following things have to be fixed:
- include x, xetex and xindy
- include texmf archive into installation

### CODE REVIEW

**Comment by jakobjakobson13** [comment]
Texlive builds the files into

- aarch64-unknown-linux-gnu (aarch64)
- armv8l-unknown-linux-gnueabihf (arm)
- x86_64-pc-linux-gnu (x86_64)

so the `enable.sh` script has to be adapted for each architecture.

And the aarch64 build fails to a missing `libpng` library.

**Comment by jakobjakobson13** [comment]
The `install-tl` (so the installation program on the downloaded DVD) runs the following scripts after the extraction of the packages:
```
running mktexlsr /usr/lib/sdk/texlive/texmf-dist ...
writing fmtutil.cnf to /usr/lib/sdk/texlive/texmf-dist/web2c/fmtutil.cnf
writing updmap.cfg to /usr/lib/sdk/texlive/texmf-dist/web2c/updmap.cfg
writing language.dat to /usr/lib/sdk/texlive/texmf-var/tex/generic/config/language.dat
writing language.def to /usr/lib/sdk/texlive/texmf-var/tex/generic/config/language.def
writing language.dat.lua to /usr/lib/sdk/texlive/texmf-var/tex/generic/config/language.dat.lua
running mktexlsr /usr/lib/sdk/texlive/texmf-var /usr/lib/sdk/texlive/texmf-config /usr/lib/sdk/texlive/texmf-dist ...
running updmap-sys --nohash ...done
re-running mktexlsr /usr/lib/sdk/texlive/texmf-var /usr/lib/sdk/texlive/texmf-config ...
setting up ConTeXt cache: running mtxrun --generate ...done
pre-generating all format files, be patient...
running fmtutil-sys --no-error-if-no-engine=luajithbtex,luajittex,mfluajit --no-strict --all ...done
running package-specific postactions
```

**Comment by jakobjakobson13** [comment]
@Alexander-Wilms The `aarch64` build fails to a missing `libpng` library, even though it can be found in the `arm` and `x86_64` builds. Do you know if this is due to the build process of texlive or is it a general problem with the combination `libpng` and `aarch64`?

**Comment by hfiguiere** [comment]
This should be closed in favor of #34.

**Comment by jakobjakobson13** [comment]
Further work will be done in #34.

**Pull request closed without merging**
