### PR TITLE
update biber and biblatex

### PR DESCRIPTION
**Pull request by jakobjakobson13**

### CODE REVIEW

**Comment by mpanhans** [comment]
There is a weird problem with using biblatex and biber in TexStudio. The workaround in https://github.com/flathub/org.texstudio.TeXstudio/issues/94 that worked before this pull request was merged no longer works. Instead that workaround results in a new error that biber and biblatex versions are incompatible:
"This means that your biber (2.18) and biblatex (3.17) versions are incompatible."
This is weird because biblatex (3.18) is specified in this code merge, so I cannot figure out where the (3.17) comes from.
What do you think about pulling the latest biblatex from sourceforge as was done before this pull request, instead of from github, and also pulling the latest patch which is (3.18b)?
This would be:
url: https://sourceforge.net/projects/biblatex/files/biblatex-3.18/biblatex-3.18b.tds.tgz
sha256: 9714295434cfe78d6c58de3460876f6d4b254bf88a4acd3d3112d3ccfe8d826b
dest-filename: biblatex.tds.tgz

**Comment by jakobjakobson13** [comment]
I found a similar issue on stackexchange: https://tex.stackexchange.com/questions/633088/biber-biblatex-error-after-update.
Could you try to delete the .aux, .bbl and .bcf file of your project and recompile?

**Comment by mpanhans** [comment]
Thanks for the quick response. Yes I always delete all the auxiliary files. Here is exactly what I have done to reproduce this issue, and I've done it on two separate machines:
1. Fresh install of latest versions of TexStudio and Texlive from Flathub.
2. Enter a shell inside of TS with flatpak run --command=sh org.texstudio.TeXstudio
3. Navigate to and open /app/texlive/texmf-dist/tex/latex/biblatex/biblatex.sty
That biblatex.sty file, for me, always says biblatex version 3.17. Which is unexpected.

And if I then roll back texlive to an earlier commit, it says biblatex version 3.16, as is expected. So that's why I thought it was a change from this code merge that was not behaving as desired.

**Comment by jakobjakobson13** [comment]
Perhaps this issue was also due to the change from the dts version to the non-dts version. 
But let's see if the new version (and going back to the dts package) solves this issue.

**Comment by mpanhans** [comment]
Thank you, I've done a few checks and the test build in #101 correctly shows biblatex 3.18. I really appreciate your prompt attention on this!

**Pull request merged**
