### PR TITLE
Update texlive to texlive2019

### PR DESCRIPTION
**Pull request by jakobjakobson13**

### CODE REVIEW

**Comment by jakobjakobson13** [comment]
> Build [3116 failed](https://flathub.org/builds/#/builders/32/builds/3116)

@Alexander-Wilms Could you please point out my mistake in this pull request? I thought it should work fine as it is. Thanks in advance. Regards

**Comment by barthalion** [comment]
It's somewhat infra issue, I will try to solve it this week.

**Comment by jakobjakobson13** [comment]
Any news?

**Comment by Alexander-Wilms** [comment]
bot, build

**Comment by Alexander-Wilms** [comment]
Thanks a lot

**Pull request merged**
