### PR TITLE
correcting perl installation path2

### LINKED ISSUE #72: epstopdf does not work
Hello,

Thanks for providing texlive as a flatpak

I try to use texlive with the flathub versions of both TexStudio and TexMaker. But in both cases I cannot get a converted pdf.

In TexStudio, I receive also the error

`perl: error while loading shared libraries: libperl.so: cannot open shared object file: No such file or directory system returned with code 32512`

Attached you find a MWE.
[testepstopdf.zip](https://github.com/flathub/org.freedesktop.Sdk.Extension.texlive/files/7958911/testepstopdf.zip)

My versions:
```
TeXstudio                                   org.texstudio.TeXstudio                    4.2.0 
TeX Live Sdk extension                      org.freedesktop.Sdk.Extension.texlive      20210325
Texmaker                                    net.xm1math.Texmaker                       5.1.2
```

System: Xubuntu 20.04.3, no Texlive installed via repositories

### PR DESCRIPTION
**Pull request by bztd**
trying to fix https://github.com/flathub/org.freedesktop.Sdk.Extension.texlive/issues/72

texlive needs to be mounted in /app/texlive

### CODE REVIEW

**Comment by bztd** [comment]
@hfiguiere I have been trying to change the permissions of some files in the destination path in my local tests, but there has been no success. Any interaction with these files causes an error, I need to make modifications after installation. Is there a procedure that allows me to modify the read, write and execution permissions?

**Comment by bztd** [comment]
@jakobjakobson13 In my local tests it seems to fix https://github.com/flathub/org.freedesktop.Sdk.Extension.texlive/issues/72.
I would have liked to do it another way but I had problems with read-only files.

**Comment by jakobjakobson13** [comment]
Could I ask you for one favour before I merge this pull request? I think the solution is much simpler. Could you try to delete the `PREFIX=${FLATPAK_DEST} ` bit in the perl-libs manifest and leave the rest of the files as they are currently (in the 23.08 branch)? In my local test perl was build fine with this configuration and given the environmental variables are set properly, epstopdf should work as well.

**Comment by bztd** [comment]
What happens is that the perl that is used to compile perl-libs is the perl of the sdk, so it will try to install them in the wrong location.
In the same way we can try it to see if this happens.

**Comment by bztd** [comment]
@jakobjakobson13 I think it is better if you make a new request.

**Pull request closed without merging**
