### PR TITLE
Fix flathub.json

### PR DESCRIPTION
**Pull request by jakobjakobson13**

### CODE REVIEW

**Comment by jakobjakobson13** [comment]
> Build [6750 failed](https://flathub.org/builds/#/builders/32/builds/6750)

Did it fail due to a wrong manifest or due to an error the upload mechanism?
[Log](https://flathub.org/builds/#/builders/10/builds/801/steps/15/logs/stdio)

**Comment by barthalion** [comment]
bot, build

**Comment by barthalion** [comment]
bot, build

**Comment by jakobjakobson13** [comment]
Somehow I got the idea this will not going anywhere. ;)

Six times of eleven it crashed with the same error message:
```python3
OverflowError: string longer than 2147483647 bytes
```
during the
```python3
flatpak run org.flatpak.flat-manager-client push https://hub.flathub.org/api/v1/build/XXXX repo
```
stage. So could it be a size issue?

**Comment by barthalion** [comment]
@jakobjakobson13 I'm not a quitter. :)

**Comment by jakobjakobson13** [comment]
> @jakobjakobson13 I'm not a quitter. :)

Thank god, I had the feeling you just liked running into a wall again and again and again.

I could however not try the current build due to the following error:
```terminal
$ flatpak install --user https://dl.flathub.org/build-repo/9629/org.freedesktop.Sdk.Extension.texlive.flatpakref
Fehler: Can't load uri https://dl.flathub.org/build-repo/9629/org.freedesktop.Sdk.Extension.texlive.flatpakref: Server returned status 404: Not Found
```

**Comment by barthalion** [comment]
bot, build

**Comment by jakobjakobson13** [comment]
> Build [10224 successful](https://flathub.org/builds/#/builders/32/builds/10224)
> To test this build, install it from the testing repository:
> 
> ```
> flatpak install --user https://dl.flathub.org/build-repo/9725/org.freedesktop.Sdk.Extension.texlive.flatpakref
> ```

I still have no luck with the installing due to the same error as previously.

**Comment by barthalion** [comment]
@jakobjakobson13 It's different issue… Underlying files are still there, so if you add it as a remote, it will work. Fixing that is on my list.

**Pull request merged**
